(in-package :al5d)

(def-fact-group lynxmotion-al5d-action-designators (action-grounding)
    (<- (desig:action-grounding ?desig (pick ?resolved-action-designator))
        (desig-prop ?desig (:type :picking))
        (desig-prop ?desig (:position ?position))
        (desig-prop ?desig (:orientation ?orientation))
        (desig:designator :action ((:position ?position)
                                    (:orientation ?orientation))
                            ?resolved-action-designator))

    (<- (desig:action-grounding ?desig (place ?resolved-action-designator))
        (desig-prop ?desig (:type :placing))
        (desig-prop ?desig (:position ?position))
        (desig-prop ?desig (:orientation ?orientation))
        (desig:designator :action ((:position ?position)
                                    (:orientation ?orientation))
                            ?resolved-action-designator))

    (<- (desig:action-grounding ?desig (approach ?resolved-action-designator))
        (desig-prop ?desig (:type :approaching))
        (desig-prop ?desig (:position ?position))
        (desig-prop ?desig (:orientation ?orientation))
        (desig:designator :action ((:position ?position)
                                    (:orientation ?orientation))
                            ?resolved-action-designator))

    (<- (desig:action-grounding ?desig (pick-and-place ?resolved-action-designator))
        (desig-prop ?desig (:type :picking-and-placing))
        (desig-prop ?desig (:from ?source-position))
        (desig-prop ?desig (:is-heading ?source-orientation))
        (desig-prop ?desig (:to ?dest-position))
        (desig-prop ?desig (:will-head ?dest-orientation))
        (desig:designator :action ((:from-position ?source-position)
                                   (:from-orientation ?source-orientation)
                                   (:to-position ?dest-position)
                                   (:to-orientation ?dest-orientation))
                            ?resolved-action-designator)))
